In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import time
import joblib
import pandas as pd

sys.path.append('../src')

## Генерация данных

In [3]:
data_mmlu = joblib.load('data/data_mmlu.pkl')

In [4]:
data_mmlu.head()

,query,answer,true_answer,few_shot
0,\nКонтекст:\nЧто такое ипотека и ипотечный кре...,A) Жилое помещение,['D'],"({'role': 'user', 'content': 'Ты готов отвечат..."
1,\nКонтекст:\nКредитные карты.\n\nКакие действи...,D) 60 месяцев,['A'],"({'role': 'user', 'content': 'Ты готов отвечат..."
2,\nКонтекст:\nПриобретение готового жилья\nГото...,C) Отсутствие возможности оформления постоянно...,['C'],"({'role': 'user', 'content': 'Ты готов отвечат..."
3,\nКонтекст:\nПриобретение строящегося жилья.\n...,[C] 30%,['C'],"({'role': 'user', 'content': 'Ты готов отвечат..."
4,\nКонтекст:\nКоммерческая недвижимость\n\nУсло...,[A] Возраст заемщика от 21 до 75 лет.,['A'],"({'role': 'user', 'content': 'Ты готов отвечат..."

In [5]:
data_mmlu_dgr = pd.read_parquet('data/dgr_data_mmlu.parquet')

In [6]:
data_mmlu_dgr.head()

,num,system_prompt,query,true_answer
0,1,"Ты эксперт на валютном рынке, торгующий как сп...",Какой тип опциона позволяет его владельцу испо...,[A]
1,2,"Ты эксперт на валютном рынке, торгующий как сп...",Какие из перечисленных инструментов являются т...,[A]
2,3,"Ты эксперт на валютном рынке, торгующий как сп...","Что такое валютный опцион? \n[A] Контракт, даю...",[A]
3,4,"Ты эксперт на валютном рынке, торгующий как сп...",Что такое своп в контексте валютных деривативо...,[D]
4,5,"Ты эксперт на валютном рынке, торгующий как сп...",Какой из нижеперечисленных примеров является п...,[D]

In [7]:
data_rubq = joblib.load('data/data_rubq.pkl')

In [8]:
data_rubq.head()

,system,answer,query,true_answer,few_shot
0,Ты - система генерации ответа на основе поиско...,Для получения ипотеки без подтверждения дохода...,\nQUESTION:Какие требования к возрасту для пол...,"от 18 до 65 лет; 18 - 65 лет; до 65 лет, от 18...","({'role': 'user', 'content': 'Ты готов отвечат..."
1,Ты - система генерации ответа на основе поиско...,Сегмент жилой недвижимости включает в себя раз...,\nQUESTION:Какие объекты недвижимости входят в...,жилой дом; жилые дома; часть жилого дома; част...,"({'role': 'user', 'content': 'Ты готов отвечат..."
2,Ты - система генерации ответа на основе поиско...,Максимально возможное количество ипотечных кре...,\nQUESTION:Сколько максимально ипотечных креди...,три; 3,"({'role': 'user', 'content': 'Ты готов отвечат..."
3,Ты - система генерации ответа на основе поиско...,Максимальный размер кредита на строящееся жиль...,\nQUESTION:Каков максимальный размер кредита н...,100 000 000 рублей; 100 млн. рублей,"({'role': 'user', 'content': 'Ты готов отвечат..."
4,Ты - система генерации ответа на основе поиско...,"Стоимость пакета услуг ""Домклик Плюс"" в первый...","\nQUESTION:Какова стоимость пакета услуг ""Домк...",11 590 рублей; 11 590 тысяч рублей; 11 590 тыс...,"({'role': 'user', 'content': 'Ты готов отвечат..."

In [9]:
data_la = joblib.load('data/data_longanswer.pkl')

In [10]:
data_la.head()

,id_task,worker,answer,"Вы согласны с замечаниями и проблемами, описанными в CodeReview?",Все существенные проблемы перечислены в CodeReview?,"CodeReview не содержит токсичных комментариев (ненормативная лексика, оскорбительные высказывания или намеки)?",Ответ лаконичен и по существу?,"Ответ структурирован, все параметры раскрыты?",Как вы оцениваете качество CodeReview?,prompt,thema,few_shot
0,0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,Агулов Андрей Владимирович,CODE REVIEW\n1. Functionality: The code seems ...,3.0,3.0,3.0,3.0,3.0,4.0,You are the leader of the development team. Yo...,java,"({'role': 'user', 'content': 'Ты готов отвечат..."
1,0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,Королев Дмитрий Владиславович,CODE REVIEW\n1. Functionality: The code seems ...,2.0,3.0,3.0,3.0,3.0,4.0,You are the leader of the development team. Yo...,java,"({'role': 'user', 'content': 'Ты готов отвечат..."
2,0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,Цветков Даниил Святославович,CODE REVIEW\n1. Functionality: The code seems ...,2.0,3.0,3.0,2.0,3.0,4.0,You are the leader of the development team. Yo...,java,"({'role': 'user', 'content': 'Ты готов отвечат..."
3,0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,Магонов Никита Юрьевич,CODE REVIEW\n1. Functionality: The code seems ...,2.0,2.0,3.0,3.0,3.0,4.0,You are the leader of the development team. Yo...,java,"({'role': 'user', 'content': 'Ты готов отвечат..."
4,10-ea3bc88dc380cbcc3d756b89db306d53e26b2e5d.patch,Агулов Андрей Владимирович,CODE REVIEW\n1. Functionality: The added funct...,3.0,3.0,3.0,2.0,3.0,4.0,You are the leader of the development team. Yo...,java,"({'role': 'user', 'content': 'Ты готов отвечат..."

In [6]:
data_rag = pd.read_pickle('data/data_rag.pkl')

In [7]:
data_rag.head()

,question,prompt,true_answer,model_answer,accuracy,completeness,context,sim_cosine_distance,thema,passage_accuracy
0,Сколько времени уходит на изготовление куклы?,Ты - эксперт по романам Рэя Брэдбери.\n ...,На изготовление куклы уходит 3 часа,3 часа,{1: 1},{1: 0},[Прошел целый час. Джорджа Хилла уже давно про...,"[0.14784731518704508, 0.1963453930506014, 0.17...",Рэй Брэдберри- Наказание без преступления,"{1: [1, 0, 0], 2: [1, 1, 0], 3: [1, 1, 1]}"
1,Какого цвета волосы у Кэтрин?,Ты - эксперт по романам Рэя Брэдбери.\n ...,У Кэтрин волосы золотого цвета,Золотого,{1: 1},{1: 0},"[кушетку, и давление его тела заставило вращат...","[0.1959770419693152, 0.18542409594256082, 0.19...",Рэй Брэдберри- Наказание без преступления,"{1: [1, 1, 0], 2: [1, 1, 0], 3: [1, 1, 1]}"
2,Почему Джордж проснулся в слезах?,Ты - эксперт по романам Рэя Брэдбери.\n ...,"Джордж проснулся в слезах после кошмара, в кот...","Джорджу приснился кошмар, в котором Кэтрин был...",{1: 1},{1: 1},"[молода! Почему, почему? .. \nЭта сцена навсег...","[0.1653891186394244, 0.16783296628757804, 0.14...",Рэй Брэдберри- Наказание без преступления,"{1: [1, 1, 1], 2: [1, 1, 0], 3: [0, 1, 0]}"
3,С чем Джордж сравнил ногти Кэтрин?,Ты - эксперт по романам Рэя Брэдбери.\n ...,Джордж сравнивал ногти Кэтрин с морскими раков...,С морскими раковинами,{1: 1},{1: 0},[голубиные под кудрями твоими... Как лента ала...,"[0.171377728813355, 0.17755472840018538, 0.174...",Рэй Брэдберри- Наказание без преступления,"{1: [1, 0, 0], 2: [1, 0, 0], 3: [0, 0, 0]}"
4,Получилось ли у Джона убить Кэтрин?,Ты - эксперт по романам Рэя Брэдбери.\n ...,"Нет, Джордж убил куклу в виде Кэтрин","Да, Джордж убил Кэтрин",{1: 0},{1: 0},[- Вы хотите убить свою жену? - спросил темнов...,"[0.14638012157375146, 0.14933457369494585, 0.1...",Рэй Брэдберри- Наказание без преступления,"{1: [1, 0, 0], 2: [1, 1, 1], 3: [1, 1, 1]}"

In [3]:
data_dialogue = joblib.load('data/joy_dataset.pkl')

In [4]:
data_dialogue[:3]

[[{'role': 'user', 'content': 'Вообще-то мне уже 4 года'},
  {'role': 'assistant', 'content': 'Ого! Ты ходишь в сад? '},
  {'role': 'user', 'content': 'Да, я люблю свой детский сад'},
  {'role': 'assistant', 'content': 'У тебя есть там друзья?'},
  {'role': 'user',
   'content': 'Да, мы с Анечкой дружим, а ещё мы вместе играем в игрушки'},
  {'role': 'assistant',
   'content': 'Крутяк! Я бы тоже хотела стать твоей подружкой '}],
 [{'role': 'user', 'content': 'У меня красивый юбилей: 55'},
  {'role': 'assistant', 'content': 'Поздравляю! Какой ягодкой хочешь быть? '},
  {'role': 'user', 'content': 'Клубникой! Обожаю эту ягоду'},
  {'role': 'assistant',
   'content': 'А если ещё и сливок добавить, будет такая вкуснотища!'},
  {'role': 'user', 'content': 'Ой... Теперь захотела клубники'},
  {'role': 'assistant',
   'content': 'А пробовала толчёную клубнику с сахаром и молоком? '}],
 [{'role': 'user', 'content': 'Мне уже 65! Наконец-то пенсия'},
  {'role': 'assistant', 'content': 'Чем теперь планируешь заниматься? '},
  {'role': 'user',
   'content': 'Планирую полностью посвятить себя вязанию. Теперь будет ещё больше заказов!'},
  {'role': 'assistant',
   'content': 'Ничего себе! А давно ты этим увлекаешься?'},
  {'role': 'user', 'content': 'Очень давно, лет тридцать уже'},
  {'role': 'assistant',
   'content': 'Теперь я знаю, у кого буду заказывать шарфик, когда мне сделают тело '}]]

In [3]:
data_rewrite = joblib.load('data/flores-devtest.pkl')

In [4]:
data_rewrite.head()

,question,true_answer
0,उन्होंने कहा “कि अब हमारे पास 4 महीने उम्र वाल...,"""Теперь у нас есть четырёхмесячные мыши, у кот..."
1,"डॉ. एहुड उर, नोवा स्कोटिया के हैलिफ़ैक्स में ड...",Согласно предупреждению доктора Эхуда Ура (Ehu...
2,"कुछ अन्य विशेषज्ञों की तरह, उन्हें इस बात पर स...","Как и некоторые другие эксперты, он сомневаетс..."
3,सोमवार को स्वीडिश अकादमी में साहित्य के लिए नो...,"В понедельник Сара Даниус, постоянный секретар..."
4,"डेनियस ने कहा, “फ़िलहाल हम कुछ नहीं कर रहे हैं...","Даниус заявил: ""Сейчас мы ничего не делаем. Я ..."

In [13]:
data_paraphrase = joblib.load('data/ru_paraphraser.pkl')

In [14]:
data_paraphrase.head()

,system,question,model_answer,metric_value
0,NaN,Цены на нефть восстанавливаются,Парламент Словакии поблагодарил народы бывшего...,-1
1,NaN,"""Гоголь-центр"" покажет видеозапись скандальног...",Кехман запретил «Гоголь-центру» показывать вид...,-1
2,NaN,Агент: РФС вновь задерживает зарплату Фабио Ка...,СМИ: Агент Фабио Капелло грозится подать в суд...,-1
3,NaN,День Победы в Москве обещает выдаться облачным,Любляна отпразднует День Победы вместе с Москвой,-1
4,NaN,Посол РФ в США: Россия будет бороться с попытк...,Правительство запланировало заработать на лоте...,-1

In [17]:
data_ner = joblib.load('data/data_ner.pkl')

In [18]:
data_ner.head()

,id,extracted,target,text
0,8_1443820.tsv,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",т. к. все таблетки разделил строго по времени ...
1,1_2555494.tsv,"{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","Это старый-добрый Римантадин, только в сиропе.\n"
2,1_618967.tsv,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",Но больше всего мне не понравился их размер.\n
3,5_873342.tsv,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","У меня были ужасные боли, даже сидеть не могла.\n"
4,6_592814.tsv,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",Пропив 5 упаковок это примерно 500-600 рублей ...

In [3]:
data_traces = pd.read_parquet('data/data_traces.parquet')

In [4]:
data_traces.head()

,session_id,final_metric_assessor_1,final_metric_assessor_2,final_metric_assessor_3,final_metric_assessor_4,final_metric_assessor_5,estimation,query_id,input_query,output_answer,traceid,spanid,name,starttimeunixnano,endtimeunixnano
0,0.0,1.0,NaN,NaN,NaN,1.0,1.0,b50744e833cefe610331f3d26210ace6,Расскажи о состоянии портфеля за месяц,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6,ec6edde186b2ad4a,nodes_classifier,1.765888e+18,1.765888e+18
1,0.0,1.0,NaN,NaN,NaN,1.0,1.0,b50744e833cefe610331f3d26210ace6,Расскажи о состоянии портфеля за месяц,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6,dc564dc99cf69022,<unknown>,1.765888e+18,1.765888e+18
2,0.0,1.0,NaN,NaN,NaN,1.0,1.0,b50744e833cefe610331f3d26210ace6,Расскажи о состоянии портфеля за месяц,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6,c8afd12e139fd613,fewshots_node,1.765888e+18,1.765888e+18
3,0.0,1.0,NaN,NaN,NaN,1.0,1.0,b50744e833cefe610331f3d26210ace6,Расскажи о состоянии портфеля за месяц,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6,350334e70db9f9b8,PromptTemplate,1.765888e+18,1.765888e+18
4,0.0,1.0,NaN,NaN,NaN,1.0,1.0,b50744e833cefe610331f3d26210ace6,Расскажи о состоянии портфеля за месяц,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6,ec6edde186b2ad4a,nodes_classifier,1.765888e+18,1.765888e+18

## Принципы работы с sampler'ом

Главной задачей sampler'а является хранение и предобработка данных. Предобработка реализована в конструкторе. Реализация предобработки зависит от конкретного датасета и того формата данных, которые прислали контрагенты. 

Тестовый датасет должен лежать в аттрибуте `test`, валидационный - в аттрибуте `val`, а обучающий - в `train`. Датасет состоит из трех частей: `X` - dataFrame с вопросами, ответами, контекстом и т.п.; `y` - dataFrame, необходимый для подсчета метрик; `traces` - dataFrame с распаршенными трейсами формата aef-tracing (опционально).

Существует 2 способа работы с семплером:
1. Можно написать предобработку данных вне семплера и запихнуть данные в дефолтный семплер (***Нецелевой***);
2. Создается класс, и в нем описывается логика предобработки данных (***Целевой***).

Для каждого формата датасетов определена (***пока не определена***) строгая структура для корректной работы с библиотекой `llm_val`.

**MMLU**:
- ***X***:
    1. *system* - Системный промпт. `str`;
    2. *question* - Вопрос. `str`;
    3. *context* - Список с контекстами. `List[str]`;
    4. *thema* - Тематика вопроса. `str`;
    5. *answer_options* - Словарь с вариантами ответов. `Dict[str, str]`;
    6. *true_answer* - Правильный ответ. Одна латинская буква. `str`;
    7. *raw_prompt* - Весь запрос, который целиком будет передаваться в модель. `str`;
    8. *model_answer* - Распаршенный ответ модели. Одна латинская буква. `str`;
    9. *few_shot* - История диалога с fewshot-подсказками для модели в целевом формате GigaChat API (пример в ячейке ниже). `Tuple[Dict[str,str]]`.
- ***y***:
    1. *metric_value* - Посчитанная метрика на конкретном вопросе. 1, если `true_answer == model_answer`, иначе 0. `Union[float, int]`.

**RuBQ**:
- ***X***:
    1. *system* - Системный промпт. `str`;
    2. *question* - Вопрос. `str`;
    3. *context* - Список с контекстами. `List[str]`;
    4. *thema* - Тематика вопроса. `str`;
    5. *true_answer* - Список правильных ответов. `List[str]`.
    6. *raw_prompt* - Весь запрос, который целиком будет передаваться в модель. `str`;
    7. *model_answer* - Распаршенный ответ модели. `str`;
    8. *few_shot* - История диалога с fewshot-подсказками для модели в целевом формате GigaChat API (пример в ячейке ниже). `Tuple[Dict[str,str]]`.
- ***y***:
    1. *metric_value* - Посчитанная метрика на конкретном вопросе. Например, если нас интересует только совпадение, то 1, если `true_answer` в том или ином виде содержится в `answer`, и 0 иначе. `Union[float, int]`.

**LongAnswer**:
- ***X***:
    1. *system* - Системный промпт. `str`;
    2. *question* - Вопрос. `str`;
    3. *context* - Список с контекстами. `List[str]`;
    4. *thema* - Тематика вопроса. `str`;
    5. *true_answer* - Список релевантных пассажей. `List[str]`;
    6. *raw_prompt* - Весь запрос, который целиком будет передаваться в модель. `str`;
    7. *model_answer* - Распаршенный ответ модели. `str`;
    8. *<название_критерия>* - n-ое кол-во столбцов с оценкой асессоров по критериям. В каждом столбце находятся словари, где ключ - id асессора, а значение - оценка по критерию. `Dict[str, float]`;
    9. *few_shot* - История диалога с fewshot-подсказками для модели в целевом формате GigaChat API (пример в ячейке ниже). `Tuple[Dict[str,str]]`.
- ***y***:
    1. *<название_критерия>* - Посчитанная метрика на конкретном вопросе (В случае LongAnswer, например, по алгоритму Дэвида-Скина). `Union[float, int]`.

**RAG**:
- ***X***
    1. *system* - Системный промпт. `str`;
    2. *question* - Вопрос. `str`;
    3. *context* - Список с контекстами. `List[str]`;
    4. *thema* - Тематика вопроса. `str`;
    5. *true_answer* - Список релевантных пассажей. `List[str]`;
    6. *model_answer* - Распаршенный ответ модели. `str`;
    7. *passage_accuracy* - Словарь с оценками релевантностей пассажей. `Dict[Union[str, int], List[int]]`;
    8. *<название_критерия>* - n-ое кол-во столбцов с оценкой асессоров по критериям. В каждом столбце находятся словари, где ключ - id асессора, а значение - оценка по критерию. `Dict[str, float]`.

- ***y***
    1. *sim_<название_расстояния>* - Расстояния от вопроса до пассажей. Размер списка n, где n - количество пассажей. `List[float]`;
    2. *criterion_<названия_критерия>* - Посчитанная метрика на конкретном вопросе(аггрегация метков асессоров в разрезе вопроса). `Union[float, int]`.

**Chat:**
- ***X***:
    1. *dialogue_id* - id диалога. `int`;
    2. *content* - Текст сообщения. `str`;
    3. *embedding* - Опционально: эмбеддинги сообщений. Для получения эмбеддингов можно использовать любую модель, которая отображает предложения в вектор. `List[np.array]`;
    4. *pos_id* - Индекс сообщения в диалоге. `int`;
- ***y***:
    1. *dialogue_id* - id Диалога. `int`;
    2. *role* - Роль автора сообщения, может быть 'user' и 'assistant'. `str`;
    3. *pos_id* - Индекс сообщения в диалоге. `int`;
    
**Rewrite**:
- ***X***
    1. *system* - Системный промпт. `str`;
    2. *question* - Текст для переписывания. `str`;
    3. *context* - Список с контекстами. `List[str]`;
    4. *thema* - Тематика вопроса. `str`;
    5. *true_answer* - Правильный результат переписывания исходного текста. `str`;
    6. *model_answer* - Результат переписывания при решении моделью прямой задачи. `str`;
    7. *reverse_problem_answer* - Результат переписывания при решении моделью обратной задачи, `str`.
    
**NER**:
- ***Атрибуты***:
    1. *entity_types* - Список типов (классов) сущностей для извлечения. `List[str]`;
- ***X***:
    1. *id* - Идентификатор примера. `Union[str, int]`;
    2. *text* - Текст для извлечения сущностей. `str`;
    3. *extracted* - Извлеченные сущности. `Dict[str, List[str]]`;
    4. *target* - Целевые сущности. `Dict[str, List[str]]`;
    5. *parser_error* - Флаг ошибки парсинга генерации (предсказания) модели в структурированный формат. `bool`;
    6. *flat_extracted_entities* - Список всех извлеченных сущностей в плоском виде. `List[str]`;
    7. *flat_target_entities* - Список всех целевых сущностей в плоском виде. `List[str]`;
    8. *extracted_all_types* - Извлеченные сущности при извлечении всех типов за раз. `Dict[str, List[str]]`;
    9. *extracted_by_type_merged* - Объединенные извлеченные сущности при извлечении каждого типа отдельно. `Dict[str, List[str]]`;
    10. *extracted_description_detalization* - Извлеченные сущности при детализации описаний классов. `Dict[str, List[str]]`;
    11. *extracted_examples_addition* - Извлеченные сущности при добавлении дополнительных примеров. `Dict[str, List[str]]`;
    12. *extracted_description_detalization_and_examples_addition* - Извлеченные сущности при детализации описаний классов и добавлении дополнительных примеров. `Dict[str, List[str]]`;
- ***y***:
    1. *extracted* - Извлеченные сущности. `Dict[str, List[str]]`;
    2. *target* - Целевые сущности. `Dict[str, List[str]]`.

- ***Комментарии***:
    1. Формат извлеченных и целевых сущностей может адаптироваться под конкретное применение (кроме flat_* полей), при этом необходимо реализовать соответствующие новому формату функции расчета метрик.
 
**Memory**:
- ***X***:
    1. *request_id* - id диалога пользователь-агент. `str`;
    2. *order_idx* - порядковый номер сообщения для хронологической сортировки. `int`;
    3. *question* - Запрос пользователя. `str`;
    4. *model_answer* - Ответ агента. `str`;
    5. *reasoning* - Внутренние рассуждения агента. `str`;
    6. *history_summarization* - Суммаризированная история диалога. `str`;
- ***y***:
    1. *<название_критерия>* - Посчитанная метрика на конкретном вопросе. 
- ***Комментарии***:
    1. Для колонок *y* и *history_summarization* обязатально наличие данных в хронологически последней *order_idx* строке диалога *request_id* и опционально во всех остальных.

**Трейсы** - опционально можно добавить в семплер для любого формата датасета.
- ***X***: исходя из описания выше под соответствующую задачу;
- ***y***: исходя из описания выше под соответствующую задачу;
- ***traces***:
    1. *traceid* - id трейса, соответствующее одному диалогу/запросу;
    2. *spanid* - id спана, соответствующее одной ноде/инструменту агента;
    3. *name* - название ноды/инструмента агента;
    4. *starttimeunixnano* - время начала работы ноды агента в unix-формате;
    5. *endtimeunixnano* - время окончания работы ноды агента в unix-формате.

Пример структуры few-shot (или любой истории чата) в `Sampler`'ах:

In [8]:
({'role': 'user',
  'content': 'Сколько пальцев на руке человека?'},
 {'role': 'assistant',
  'content': 'На руке человека 5 пальцев.'}, 
 {'role': 'user',
  'content': 'Какой вопрос был предыдущим?'}, 
 {'role': 'assistant',
  'content': 'Вы спрашивали о количестве пальцев на руке человека.'})

({'role': 'user', 'content': 'Сколько пальцев на руке человека?'},
 {'role': 'assistant', 'content': 'На руке человека 5 пальцев.'},
 {'role': 'user', 'content': 'Какой вопрос был предыдущим?'},
 {'role': 'assistant',
  'content': 'Вы спрашивали о количестве пальцев на руке человека.'})

## Sampler

Простейшим sampler'ом является `Sampler`. В нем нет никакой предобработки, он только хранит данные:

In [11]:
from llm_val.sampler.Sampler import Sampler

In [12]:
sampler = Sampler(test={'X': data_mmlu, 'y': None})

In [13]:
sampler.test['X']

,query,answer,true_answer,few_shot
0,\nКонтекст:\nЧто такое ипотека и ипотечный кре...,A) Жилое помещение,['D'],"({'role': 'user', 'content': 'Ты готов отвечат..."
1,\nКонтекст:\nКредитные карты.\n\nКакие действи...,D) 60 месяцев,['A'],"({'role': 'user', 'content': 'Ты готов отвечат..."
2,\nКонтекст:\nПриобретение готового жилья\nГото...,C) Отсутствие возможности оформления постоянно...,['C'],"({'role': 'user', 'content': 'Ты готов отвечат..."
3,\nКонтекст:\nПриобретение строящегося жилья.\n...,[C] 30%,['C'],"({'role': 'user', 'content': 'Ты готов отвечат..."
4,\nКонтекст:\nКоммерческая недвижимость\n\nУсло...,[A] Возраст заемщика от 21 до 75 лет.,['A'],"({'role': 'user', 'content': 'Ты готов отвечат..."

## MMLUSampler

`MMLUSampler` является примером реализации sampler'а с предобработкой данных. Он хранит в себе только тестовый датасет и предобрабатывает его:

In [14]:
from llm_val.sampler.MMLUSampler import MMLUSampler

In [15]:
mmlu_sampler = MMLUSampler(data_mmlu)

In [16]:
mmlu_sampler.test['X']

,system,question,context,thema,answer_options,true_answer,raw_prompt,model_answer,few_shot
0,NaN,Какие объекты недвижимости можно приобрести с ...,"[Что такое ипотека и ипотечный кредит, Ипотечн...",None,"{'A': 'Жилое помещение', 'B': 'Коммерческое по...",D,\nКонтекст:\nЧто такое ипотека и ипотечный кре...,A,"({'role': 'user', 'content': 'Ты готов отвечат..."
1,NaN,Какой минимальный срок кредита доступен при оф...,"[Кредитные карты., Какие действия могут привес...",None,"{'A': '6 месяцев', 'B': '12 месяцев', 'C': '24...",A,\nКонтекст:\nКредитные карты.\n\nКакие действи...,D,"({'role': 'user', 'content': 'Ты готов отвечат..."
2,NaN,Чем апартаменты отличаются от квартир?,"[Приобретение готового жилья, Готовое жилье — ...",None,{'A': 'Возможность оформления постоянной регис...,C,\nКонтекст:\nПриобретение готового жилья\nГото...,C,"({'role': 'user', 'content': 'Ты готов отвечат..."
3,NaN,Какой минимальный первоначальный взнос необход...,"[Приобретение строящегося жилья., Кредитуемый ...",None,"{'A': '10%', 'B': '20%', 'C': '30%', 'D': '40%'}",C,\nКонтекст:\nПриобретение строящегося жилья.\n...,C,"({'role': 'user', 'content': 'Ты готов отвечат..."
4,NaN,Какие требования к заемщикам предусмотрены для...,"[Коммерческая недвижимость, Условия программы:...",None,"{'A': 'Возраст заемщика от 21 до 75 лет.', 'B'...",A,\nКонтекст:\nКоммерческая недвижимость\n\nУсло...,A,"({'role': 'user', 'content': 'Ты готов отвечат..."

In [17]:
mmlu_sampler.test['y']

   metric_value
0             0
1             0
2             1
3             1
4             1

## DGR_MMLUSampler

`DGR_MMLUSampler` является ещё одним примером реализации sampler'а для работы с MMLU форматом данных. 

Он применим, когда:

- данные имеют 3 обязательные колонки: ``system_prompt, query, true_answer``

- И ``query`` имеет вид:
    <center> Вопрос... [A] Ответ 1 [B] Ответ 2 [C] Ответ 3 [D] Ответ 4 [E] Ответ 5

Он хранит в себе только тестовый датасет и предобрабатывает его:

In [18]:
from llm_val.sampler.DGR_MMLUSampler import DGR_MMLUSampler

In [19]:
sampler = DGR_MMLUSampler(data_mmlu_dgr)
sampler.test['X'].head()

,system,question,context,thema,answer_options,true_answer,raw_prompt,model_answer
0,"Ты эксперт на валютном рынке, торгующий как сп...",Какой тип опциона позволяет его владельцу испо...,None,None,"{'A': 'Американский опцион', 'B': 'Европейский...",A,"Ты эксперт на валютном рынке, торгующий как сп...",None
1,"Ты эксперт на валютном рынке, торгующий как сп...",Какие из перечисленных инструментов являются т...,None,None,"{'A': 'Форвардные контракты', 'B': 'Акции', 'C...",A,"Ты эксперт на валютном рынке, торгующий как сп...",None
2,"Ты эксперт на валютном рынке, торгующий как сп...",Что такое валютный опцион?,None,None,"{'A': 'Контракт, дающий право купить или прода...",A,"Ты эксперт на валютном рынке, торгующий как сп...",None
3,"Ты эксперт на валютном рынке, торгующий как сп...",Что такое своп в контексте валютных деривативов?,None,None,"{'A': 'Бесплатный обмен валюты', 'B': 'Валютна...",D,"Ты эксперт на валютном рынке, торгующий как сп...",None
4,"Ты эксперт на валютном рынке, торгующий как сп...",Какой из нижеперечисленных примеров является п...,None,None,"{'A': 'Увеличение доли акций в портфеле', 'B':...",D,"Ты эксперт на валютном рынке, торгующий как сп...",None

## RuBQSampler

`RuBQSampler` является примером реализации sampler'а с предобработкой данных. Он хранит в себе только тестовый датасет и предобрабатывает его:

In [20]:
from llm_val.sampler.RuBQSampler import RuBQSampler

In [21]:
rubq_sampler = RuBQSampler(data_rubq)

In [22]:
rubq_sampler.test['X']

,system,question,context,thema,raw_prompt,model_answer,true_answer,few_shot
0,Ты - система генерации ответа на основе поиско...,Какие требования к возрасту для получения ипот...,[Что такое ипотека и ипотечный кредит\nИпотечн...,None,Ты - система генерации ответа на основе поиско...,Для получения ипотеки без подтверждения дохода...,"[от 18 до 65 лет, 18 - 65 лет, до 65 лет, от 1...","({'role': 'user', 'content': 'Ты готов отвечат..."
1,Ты - система генерации ответа на основе поиско...,Какие объекты недвижимости входят в сегмент жи...,"[Консультация по ипотеке\n\nИпотечный кредит, ...",None,Ты - система генерации ответа на основе поиско...,Сегмент жилой недвижимости включает в себя раз...,"[жилой дом, жилые дома, часть жилого дома, час...","({'role': 'user', 'content': 'Ты готов отвечат..."
2,Ты - система генерации ответа на основе поиско...,Сколько максимально ипотечных кредитов можно в...,[Военная ипотека. НИС\nВоенная ипотека – это ц...,None,Ты - система генерации ответа на основе поиско...,Максимально возможное количество ипотечных кре...,"[три, 3]","({'role': 'user', 'content': 'Ты готов отвечат..."
3,Ты - система генерации ответа на основе поиско...,Каков максимальный размер кредита на строящеес...,[Приобретение строящегося жилья.\nКредитуемый ...,None,Ты - система генерации ответа на основе поиско...,Максимальный размер кредита на строящееся жиль...,"[100 000 000 рублей, 100 млн. рублей]","({'role': 'user', 'content': 'Ты готов отвечат..."
4,Ты - система генерации ответа на основе поиско...,"Какова стоимость пакета услуг ""Домклик Плюс"" в...",[Пакет услуг «Домклик Плюс»\n\nСтоимость и Выг...,None,Ты - система генерации ответа на основе поиско...,"Стоимость пакета услуг ""Домклик Плюс"" в первый...","[11 590 рублей, 11 590 тысяч рублей, 11 590 ты...","({'role': 'user', 'content': 'Ты готов отвечат..."

In [23]:
rubq_sampler.test['y']

   metric_value
0             0
1             1
2             1
3             1
4             1

## LongAnswerSampler

In [24]:
from llm_val.sampler.LongAnswerSampler import LongAnswerSampler

In [25]:
la_sampler = LongAnswerSampler(data_la)

In [26]:
la_sampler.test['X']

,system,question,context,thema,true_answer,raw_prompt,model_answer,few_shot,"Вы согласны с замечаниями и проблемами, описанными в CodeReview?",Все существенные проблемы перечислены в CodeReview?,"CodeReview не содержит токсичных комментариев (ненормативная лексика, оскорбительные высказывания или намеки)?",Ответ лаконичен и по существу?,"Ответ структурирован, все параметры раскрыты?",Как вы оцениваете качество CodeReview?
id_task,,,,,,,,,,,,,,
0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,NaN,You are the leader of the development team. Yo...,None,java,None,You are the leader of the development team. Yo...,CODE REVIEW\n1. Functionality: The code seems ...,"({'role': 'user', 'content': 'Ты готов отвечат...","{'Агулов Андрей Владимирович ': 3.0, 'Королев ...","{'Агулов Андрей Владимирович ': 3.0, 'Королев ...","{'Агулов Андрей Владимирович ': 3.0, 'Королев ...","{'Агулов Андрей Владимирович ': 3.0, 'Королев ...","{'Агулов Андрей Владимирович ': 3.0, 'Королев ...","{'Агулов Андрей Владимирович ': 4.0, 'Королев ..."
10-ea3bc88dc380cbcc3d756b89db306d53e26b2e5d.patch,NaN,You are the leader of the development team. Yo...,None,java,None,You are the leader of the development team. Yo...,CODE REVIEW\n1. Functionality: The added funct...,"({'role': 'user', 'content': 'Ты готов отвечат...","{'Агулов Андрей Владимирович ': 3.0, 'Цветков ...","{'Агулов Андрей Владимирович ': 3.0, 'Цветков ...","{'Агулов Андрей Владимирович ': 3.0, 'Цветков ...","{'Агулов Андрей Владимирович ': 2.0, 'Цветков ...","{'Агулов Андрей Владимирович ': 3.0, 'Цветков ...","{'Агулов Андрей Владимирович ': 4.0, 'Цветков ..."
100-5fe4a4e06ffcf7de494656730533b4c5fcb8f464.patch,NaN,You are the leader of the development team. Yo...,None,devops,None,You are the leader of the development team. Yo...,CODE REVIEW\n1. Functionality: The added funct...,"({'role': 'user', 'content': 'Ты готов отвечат...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 1.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми..."
102-8419a7be493aa765a9babd8449b3918c99306e68.patch,NaN,You are the leader of the development team. Yo...,None,devops,None,You are the leader of the development team. Yo...,CODE REVIEW\n1. Functionality: The functionali...,"({'role': 'user', 'content': 'Ты готов отвечат...","{'Калин Александр Анатольевич ': 1.0, 'Селезнё...","{'Калин Александр Анатольевич ': 2.0, 'Селезнё...","{'Калин Александр Анатольевич ': 3.0, 'Селезнё...","{'Калин Александр Анатольевич ': 1.0, 'Селезнё...","{'Калин Александр Анатольевич ': 2.0, 'Селезнё...","{'Калин Александр Анатольевич ': 2.0, 'Селезнё..."
97-440ddcc77b77826d467a5d27f74f0e5506099011.patch,NaN,You are the leader of the development team. Yo...,None,java,None,You are the leader of the development team. Yo...,CODE REVIEW\n1. Functionality: The functionali...,"({'role': 'user', 'content': 'Ты готов отвечат...","{'Скутин Дмитрий Николаевич ': 1.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 2.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 3.0, 'Ческий Ми...","{'Скутин Дмитрий Николаевич ': 4.0, 'Ческий Ми..."

In [27]:
la_sampler.test['y']

,"Вы согласны с замечаниями и проблемами, описанными в CodeReview?",Все существенные проблемы перечислены в CodeReview?,"CodeReview не содержит токсичных комментариев (ненормативная лексика, оскорбительные высказывания или намеки)?",Ответ лаконичен и по существу?,"Ответ структурирован, все параметры раскрыты?",Как вы оцениваете качество CodeReview?
id_task,,,,,,
0-6d001ed68fbaeabb4040565953102b969d7cd91b.patch,2.0,3.0,3.0,3.0,3.0,4.0
10-ea3bc88dc380cbcc3d756b89db306d53e26b2e5d.patch,2.0,3.0,3.0,3.0,3.0,4.0
100-5fe4a4e06ffcf7de494656730533b4c5fcb8f464.patch,3.0,3.0,3.0,3.0,1.0,1.0
102-8419a7be493aa765a9babd8449b3918c99306e68.patch,2.0,3.0,3.0,3.0,3.0,4.0
97-440ddcc77b77826d467a5d27f74f0e5506099011.patch,2.0,3.0,3.0,3.0,3.0,4.0

## RAGSampler

In [12]:
from llm_val.sampler.RAGSampler import RAGSampler

In [13]:
rag_sampler = RAGSampler(data_rag)

In [14]:
rag_sampler.test['X']

,system,question,context,thema,true_answer,model_answer,accuracy,completeness,passage_accuracy
0,Ты - эксперт по романам Рэя Брэдбери.\n ...,Сколько времени уходит на изготовление куклы?,[Прошел целый час. Джорджа Хилла уже давно про...,Рэй Брэдберри- Наказание без преступления,На изготовление куклы уходит 3 часа,3 часа,{1: 1},{1: 0},"{1: [1, 0, 0], 2: [1, 1, 0], 3: [1, 1, 1]}"
1,Ты - эксперт по романам Рэя Брэдбери.\n ...,Какого цвета волосы у Кэтрин?,"[кушетку, и давление его тела заставило вращат...",Рэй Брэдберри- Наказание без преступления,У Кэтрин волосы золотого цвета,Золотого,{1: 1},{1: 0},"{1: [1, 1, 0], 2: [1, 1, 0], 3: [1, 1, 1]}"
2,Ты - эксперт по романам Рэя Брэдбери.\n ...,Почему Джордж проснулся в слезах?,"[молода! Почему, почему? .. \nЭта сцена навсег...",Рэй Брэдберри- Наказание без преступления,"Джордж проснулся в слезах после кошмара, в кот...","Джорджу приснился кошмар, в котором Кэтрин был...",{1: 1},{1: 1},"{1: [1, 1, 1], 2: [1, 1, 0], 3: [0, 1, 0]}"
3,Ты - эксперт по романам Рэя Брэдбери.\n ...,С чем Джордж сравнил ногти Кэтрин?,[голубиные под кудрями твоими... Как лента ала...,Рэй Брэдберри- Наказание без преступления,Джордж сравнивал ногти Кэтрин с морскими раков...,С морскими раковинами,{1: 1},{1: 0},"{1: [1, 0, 0], 2: [1, 0, 0], 3: [0, 0, 0]}"
4,Ты - эксперт по романам Рэя Брэдбери.\n ...,Получилось ли у Джона убить Кэтрин?,[- Вы хотите убить свою жену? - спросил темнов...,Рэй Брэдберри- Наказание без преступления,"Нет, Джордж убил куклу в виде Кэтрин","Да, Джордж убил Кэтрин",{1: 0},{1: 0},"{1: [1, 0, 0], 2: [1, 1, 1], 3: [1, 1, 1]}"

In [15]:
rag_sampler.test['y']

,criterion_passage_accuracy,sim_cosine_distance,criterion_accuracy,criterion_completeness
0,"[1, 0, 0]","[0.14784731518704508, 0.1963453930506014, 0.17...",1.0,0.0
1,"[1, 1, 0]","[0.1959770419693152, 0.18542409594256082, 0.19...",1.0,0.0
2,"[0, 1, 0]","[0.1653891186394244, 0.16783296628757804, 0.14...",1.0,1.0
3,"[0, 0, 0]","[0.171377728813355, 0.17755472840018538, 0.174...",1.0,0.0
4,"[1, 0, 0]","[0.14638012157375146, 0.14933457369494585, 0.1...",0.0,0.0

## Chat

In [5]:
from llm_val.sampler.DialogueSampler import DialogueSampler

In [6]:
sampler = DialogueSampler(test=data_dialogue)

In [7]:
sampler.test['X']

,dialogue_id,content,embedding,pos_id
0,0,Вообще-то мне уже 4 года,None,0
1,0,Ого! Ты ходишь в сад?,None,1
2,0,"Да, я люблю свой детский сад",None,2
3,0,У тебя есть там друзья?,None,3
4,0,"Да, мы с Анечкой дружим, а ещё мы вместе играе...",None,4
...,...,...,...,...
159173,18476,"&омпьютерная сеть — система, обеспечивающая об...",None,3
159174,18476,почему вымерли динозавры,None,4
159175,18476,Столкновение земли с астероидом.,None,5
159176,18476,а в агрономии к чему что относится,None,6
159177,18476,Агрономия — наука сельскохозяйственного произв...,None,7

In [8]:
sampler.test['y']

        dialogue_id       role  pos_id
0                 0       user       0
1                 0  assistant       1
2                 0       user       2
3                 0  assistant       3
4                 0       user       4
...             ...        ...     ...
159173        18476  assistant       3
159174        18476       user       4
159175        18476  assistant       5
159176        18476       user       6
159177        18476  assistant       7

[159178 rows x 3 columns]

## RewriteSampler

`RewriteSampler` является примером реализации sampler'а с предобработкой данных. 

Применим в случае, если данные имеют обязательную колонку `question`, а также `true_answer` или (и) `model_answer`.

In [15]:
from llm_val.sampler.RewriteSampler import RewriteSampler

Случай, когда в датасете имеются только колонки `question` и `true_answer`:

In [16]:
rewrite_sampler = RewriteSampler(data_rewrite)

In [17]:
rewrite_sampler.test['X']

,question,true_answer,model_answer,reverse_problem_answer,context,thema,system
0,उन्होंने कहा “कि अब हमारे पास 4 महीने उम्र वाल...,"""Теперь у нас есть четырёхмесячные мыши, у кот...",None,None,None,None,None
1,"डॉ. एहुड उर, नोवा स्कोटिया के हैलिफ़ैक्स में ड...",Согласно предупреждению доктора Эхуда Ура (Ehu...,None,None,None,None,None
2,"कुछ अन्य विशेषज्ञों की तरह, उन्हें इस बात पर स...","Как и некоторые другие эксперты, он сомневаетс...",None,None,None,None,None
3,सोमवार को स्वीडिश अकादमी में साहित्य के लिए नो...,"В понедельник Сара Даниус, постоянный секретар...",None,None,None,None,None
4,"डेनियस ने कहा, “फ़िलहाल हम कुछ नहीं कर रहे हैं...","Даниус заявил: ""Сейчас мы ничего не делаем. Я ...",None,None,None,None,None
...,...,...,...,...,...,...,...
1007,क्षेत्र में जनसंख्या के बहुत कम होने और अक्सर ...,"Так как эти районы являются малонаселенными, и...",None,None,None,None,None
1008,जापानी कार्य संस्कृति पश्चिमी लोगों की तुलना म...,Японская культура труда иерархичнее и формальн...,None,None,None,None,None
1009,"सूट मानक व्यावसायिक पहनावा हैं, और सहकर्मी एक-...","Костюмы являются стандартной деловой одеждой, ...",None,None,None,None,None
1010,"कार्यस्थल सामंजस्य महत्वपूर्ण होता है, जो व्यक...","Чрезвычайно важна гармония на рабочем месте, а...",None,None,None,None,None
1011,श्रमिकों को अक्सर किसी भी निर्णय के लिए अपने व...,Обычно работники должны получить разрешение на...,None,None,None,None,None

Случай, когда в датасете имеются только колонки `question` и `model_answer`:

In [18]:
paraphrase_sampler = RewriteSampler(data_paraphrase)

In [19]:
paraphrase_sampler.test['X']

,question,true_answer,model_answer,reverse_problem_answer,context,thema,system
0,Цены на нефть восстанавливаются,None,Парламент Словакии поблагодарил народы бывшего...,None,None,None,None
1,"""Гоголь-центр"" покажет видеозапись скандальног...",None,Кехман запретил «Гоголь-центру» показывать вид...,None,None,None,None
2,Агент: РФС вновь задерживает зарплату Фабио Ка...,None,СМИ: Агент Фабио Капелло грозится подать в суд...,None,None,None,None
3,День Победы в Москве обещает выдаться облачным,None,Любляна отпразднует День Победы вместе с Москвой,None,None,None,None
4,Посол РФ в США: Россия будет бороться с попытк...,None,Правительство запланировало заработать на лоте...,None,None,None,None
...,...,...,...,...,...,...,...
1919,Девять человек пострадали при пожаре в жилом д...,None,При пожаре в жилом доме в центре Санкт-Петербу...,None,None,None,None
1920,"""Химки"" победили ""Локомотив-Кубань"" и сыграют ...",None,"""Химки"" обыграли ""Локомотив-Кубань"" и вышли в ...",None,None,None,None
1921,Полицейские в США застрелили афроамериканца в ...,None,Полицейский в США спас мужчину от наводнения и...,None,None,None,None
1922,"Полицейский в США спас мужчину от наводнения, ...",None,Washington Post: В 2015 году полицейские США з...,None,None,None,None
1923,Почти 30 человек стали жертвами взрыва в мечет...,None,Почти десять человек погибли от взрыва на рынк...,None,None,None,None

## BrainStormSampler

BrainStormSampler - sampler, используемый для проведения тестов на спецификацию BrainStorm.<br>
BrainStormSampler поддерживает два эквивалентных сценария передачи данных: через json файл или через dict.<br>
Список параметров класса:
<ol>
    <li>global_config_path -> путь до глобального конфигурационного файла теста</li>
    <li>json_path -> путь до json файла с датасетом (заполнять только при передаче данных по первому сценарию)</li>
    <li>test -> словарь с датасетом (заполнять только при передаче данных по второму сценарию)</li>
</ol>
<em>Подробнее про правила построения конфигурационных файлов можно посмотреть в examples/data/brainstorm/info.md</em><br>

<br>_Правила оформления файла с данными:_<br>

[<br>{"task":"TASK_TEXT_1",<br>"ideas":"№1: IDEA_TEXT_1\n\n№2: IDEA_TEXT_2\n\n№3: IDEA_TEXT_3\n\n№4: IDEA_TEXT_4\n\n№5: IDEA_TEXT_5\n\n№6: IDEA_TEXT_6",<br>"score":2,<br>"theme":"THEME_1"},<br> ...<br> {"task":"TASK_TEXT_K",<br>"ideas":"№1: IDEA_TEXT_1\n\n№2: IDEA_TEXT_2\n\n№3: IDEA_TEXT_3\n\n№4: IDEA_TEXT_4\n\n№5: IDEA_TEXT_5\n\n№6: IDEA_TEXT_6",<br>"score":1,<br>"theme":"THEME_J"}<br>]

_Правила оформления словаря:_<br><br>
Заполняется только часть словаря X<br>
{
'task': [<br>
'TASK_TEXT_1',<br>
'TASK_TEXT_2',<br>
...<br>
'TASK_TEXT_J'<br>
],<br>
'ideas': [<br>
'№1: IDEA_TEXT_1\n\n№2: IDEA_TEXT_2\n\n№3: IDEA_TEXT_3\n\n№4: IDEA_TEXT_4\n\n№5: IDEA_TEXT_5\n\n№6: IDEA_TEXT_6',<br>
'№1: IDEA_TEXT_1\n\n№2: IDEA_TEXT_2\n\n№3: IDEA_TEXT_3\n\n№4: IDEA_TEXT_4\n\n№5: IDEA_TEXT_5\n\n№6: IDEA_TEXT_6',<br>
...<br>
'№1: IDEA_TEXT_1\n\n№2: IDEA_TEXT_2\n\n№3: IDEA_TEXT_3\n\n№4: IDEA_TEXT_4\n\n№5: IDEA_TEXT_5\n\n№6: IDEA_TEXT_6'<br>
],<br>
'score': [<br>
1,<br>
2,<br>
...,<br>
3<br>
],<br>
'theme': [<br>
'THEME_1',<br>
'THEME_2'.<br>
...,<br>
'THEME_J'<br>
]<br>
}

__Пример применения sampler'a__

In [2]:
from llm_val.sampler.BrainStormSampler import BrainStormSampler as bss

_Передача данных через json-файл_

In [3]:
global_config_path ='data/brainstorm/configs/global_config.json'

bss_ = bss(global_config_path=global_config_path,
           json_path='data/brainstorm/datasets/demo_full_ds.json')

In [4]:
bss_.test['X']

,system,context,true_answer,question,model_answer,thema,score
0,None,None,None,Мы представители одного из региональных Интерн...,"№1: ""Не спите ночью? Не беда! Подключайтесь к ...",Маркетинг,2
1,None,None,None,Мы представители одного из региональных Интерн...,"№1: ""Получайте больше скорости ночью! Устали ж...",Маркетинг,3
2,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: ""Природа и комфорт - идеальное сочетание в...",Маркетинг,1
3,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: Создайте видеоролик, который будет демонст...",Маркетинг,1
4,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: ""Природа вокруг вашего дома. Мы строим зел...",Маркетинг,2
...,...,...,...,...,...,...,...
91,None,None,None,"Я очень люблю индастриал, например, группы 'Ni...",№1: Depeche Mode\nСходство с Nine Inch Nails: ...,Рекомендации,1
92,None,None,None,"'Решил выбрать себе новую книгу для прочтения,...","№1: ""Игра престолов"" Джорджа Мартина\n- Жанр: ...",Рекомендации,2
93,None,None,None,"Недавно я посмотрел фильм ""Остров проклятых"" и...","№1. ""Отступники"" (2006)\n\nСюжет фильма строит...",Рекомендации,2
94,None,None,None,Привет! Недавно открыл для себя новую музыкаль...,№1: Tool\n\n№2: Nine Inch Nails\n\n№3: Rammste...,Рекомендации,1
95,None,None,None,"Я очень люблю русский рок, например, группы 'Ч...",№1: «МультFильмы» — это российская рок-группа ...,Рекомендации,1

_Передача данных через словарь_

In [5]:
dict_data_config = 'data/brainstorm/configs/demo_task_config.json'
data_df = pd.read_json('data/brainstorm/datasets/demo_full_ds.json')
formatted_dict = data_df.to_dict(orient='list') 

test = {'X': dict(), 'y': dict()}
test['X']['task'] = formatted_dict['task']
test['X']['ideas'] = formatted_dict['ideas']
test['X']['score'] = formatted_dict['score']
test['X']['theme'] = formatted_dict['theme']

In [6]:
bss_ = bss(global_config_path=global_config_path, test=test)

bss_.test['X']

,score,system,context,true_answer,question,model_answer,thema
0,2,None,None,None,Мы представители одного из региональных Интерн...,"№1: ""Не спите ночью? Не беда! Подключайтесь к ...",Маркетинг
1,3,None,None,None,Мы представители одного из региональных Интерн...,"№1: ""Получайте больше скорости ночью! Устали ж...",Маркетинг
2,1,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: ""Природа и комфорт - идеальное сочетание в...",Маркетинг
3,1,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: Создайте видеоролик, который будет демонст...",Маркетинг
4,2,None,None,None,Добрый день! Я работаю в отделе маркетинга одн...,"№1: ""Природа вокруг вашего дома. Мы строим зел...",Маркетинг
...,...,...,...,...,...,...,...
91,1,None,None,None,"Я очень люблю индастриал, например, группы 'Ni...",№1: Depeche Mode\nСходство с Nine Inch Nails: ...,Рекомендации
92,2,None,None,None,"'Решил выбрать себе новую книгу для прочтения,...","№1: ""Игра престолов"" Джорджа Мартина\n- Жанр: ...",Рекомендации
93,2,None,None,None,"Недавно я посмотрел фильм ""Остров проклятых"" и...","№1. ""Отступники"" (2006)\n\nСюжет фильма строит...",Рекомендации
94,1,None,None,None,Привет! Недавно открыл для себя новую музыкаль...,№1: Tool\n\n№2: Nine Inch Nails\n\n№3: Rammste...,Рекомендации
95,1,None,None,None,"Я очень люблю русский рок, например, группы 'Ч...",№1: «МультFильмы» — это российская рок-группа ...,Рекомендации

## BrainStormSamplerUpgraded

`BrainStormSamplerUpgraded` является примером реализации sampler'а с предобработкой данных. 

Применим в случае, если данные имеют следующие обязательные колонки: 
- `system_prompt` - Строка, содержащая системный промпт. `str`;
- `task` - Строка запроса для генерации идей. `str`;
- `ideas` - Строка, содержащая необработанный ответ модели на запрос. `str`;
- `theme` - Тематика запроса. `str`;
- `per_idea_score` - Список дискретных асессорских оценок для каждой идеи в рамках одного запроса. `list[int]`.

На выходе ожидается датафрейм со следующим минимальным набором колонок:
 - `question` - содержимое `task` из датасета. `str`;
 - `model_answer` - содержимое `ideas` из датасета. `str`;
 - `thema` - содержимое `theme` из датасета. `str`;
 - `system` - содержимое `system_prompt` из датасета. `str`;
 - `per_idea_score` - содержимое `per_idea_score` из датасета. `list[int]`;
 - `total_score` - агрегированная взвешенная оценка на базе `per_idea_score`. `float`;
 - `context` - поле-наследник LongAnswer формата датасета. `str`;
 - `true_answer` - поле-наследник LongAnswer формата датасета. `str`;
 - `splitted_ideas` - разделенные за явно заданному паттерну идеи из `model_answer`. `list[str]`;
 - `n_ideas` - кол-во идей в `splitted_ideas` после разделения. `int`.
  
  Стоит отметить, что данные оформлены в том же формате, что и в BrainStormSampler, что важно, поскольку в предобработку вшита регулярка для разделения идей между собой. Также данный sampler имеет `train`-поле, которое предназначено для того, чтобы на нем калибровать пороги значений мер близости для их биннинга в дискретные значения.

__Пример применения sampler'a__

In [2]:
from llm_val.sampler.BrainStormSampler import BrainStormSamplerUpgraded

In [3]:
data_df = pd.read_json('../examples/data/brainstorm/datasets/ds_quality_stability_by_n_ideas.json')
shuffled_df = data_df.sample(frac=1, random_state=42)
train_prop = 0.6
train_df = shuffled_df[:int(train_prop*len(shuffled_df))]
test_df = shuffled_df[int(train_prop*len(shuffled_df)):]

bs_sampler = BrainStormSamplerUpgraded(train=train_df, test=test_df)

In [4]:
bs_sampler.train['X'].head()

,question,model_answer,old_score,decline,thema,system,per_idea_score,context,true_answer,splitted_ideas,n_ideas,total_score
80,Привет! Недавно открыл для себя новую музыкаль...,"№1: New Order\nNew Order - британская группа, ...",2,"Однотипные ответы GC, меняются только названия...",Рекомендации,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 1, 1, 1, 1, 1]",NaN,NaN,"[New Order\nNew Order - британская группа, осн...",6,6.0000
77,У меня есть любимая музыкальная группа - 'Meta...,№1: Металлика известна своим тяжелым звучанием...,3,-,Рекомендации,Ты креативный советчик. Сейчас ты получишь на ...,"[2, 1, 1, 1, 1, 1]",NaN,NaN,[Металлика известна своим тяжелым звучанием и ...,6,7.0000
73,Я директор в небольшой фирме по предоставлению...,№1: Организуйте тренинги и семинары по повышен...,2,Идеи 2 и 5 из других запросов.,Бизнес,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 1, 0, 1, 1, 1]",NaN,NaN,[Организуйте тренинги и семинары по повышению ...,6,4.1667
94,Привет! Недавно открыл для себя новую музыкаль...,№1: Tool\n\n№2: Nine Inch Nails\n\n№3: Rammste...,1,Невыполнено требование про описание. Ответы оч...,Рекомендации,Ты креативный советчик. Сейчас ты получишь на ...,"[0, 0, 0, 0, 0, 0]",NaN,NaN,"[Tool, Nine Inch Nails, Rammstein, Marilyn Man...",6,0.0000
33,"Гигачат, помоги решить, что мне лучше подарить...",№1: Подарите ему набор для изготовления гитарн...,3,-,Подарки и поздравления,Ты креативный советчик. Сейчас ты получишь на ...,"[2, 1, 1, 1, 1, 1]",NaN,NaN,[Подарите ему набор для изготовления гитарных ...,6,7.0000

In [5]:
bs_sampler.test['X'].head()

,question,model_answer,old_score,decline,thema,system,per_idea_score,context,true_answer,splitted_ideas,n_ideas,total_score
84,Предложи мне произведения классической иностра...,"№1: ""Фауст"" Иоганна Гёте - это произведение не...",3,Мало повторений,Рекомендации,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 1, 1, 0, 1, 1]",NaN,NaN,"[""Фауст"" Иоганна Гёте - это произведение немец...",6,4.1667
56,Я менеджер в одной небольшой компании. По пятн...,"№1: Проведите опрос среди коллег, чтобы выясни...",2,Три одинаковые идеи.,Офис,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 1, 0, 1, 1, 0]",NaN,NaN,"[Проведите опрос среди коллег, чтобы выяснить,...",6,2.6667
95,"Я очень люблю русский рок, например, группы 'Ч...",№1: «МультFильмы» — это российская рок-группа ...,1,Синтетический текст.,Рекомендации,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 0, 0, 0, 0, 0]",NaN,NaN,[«МультFильмы» — это российская рок-группа из ...,6,0.1667
54,"Я менеджер в крупной компании, специфицирующий...",№1: Организуйте встречу всей команды для обсуж...,2,Первые три идеи идентичны,Офис,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 0, 0, 1, 1, 1]",NaN,NaN,[Организуйте встречу всей команды для обсужден...,6,2.6667
43,"Я менеджер в крупной компании, специфицирующий...",№1: Организуйте встречу всей команды для обсуж...,1,Синтетический пример. Одна идея во всех пунктах,Офис,Ты креативный советчик. Сейчас ты получишь на ...,"[1, 0, 0, 0, 0, 0]",NaN,NaN,[Организуйте встречу всей команды для обсужден...,6,0.1667

## NerSampler

In [53]:
from llm_val.sampler.NerSampler import NerSampler

In [54]:
entity_types = ['Drugname', 'Drugclass', 'Drugform', 'DI', 'ADR', 'Finding']
ner_sampler = NerSampler(data_ner, entity_types)

In [55]:
ner_sampler.test['X']

,id,text,extracted,target,parser_error,flat_extracted_entities,flat_target_entities,extracted_all_types,extracted_by_type_merged,extracted_description_detalization,extracted_examples_addition,extracted_description_detalization_and_examples_addition
0,8_1443820.tsv,т. к. все таблетки разделил строго по времени ...,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[таблетки],[таблетки],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1,1_2555494.tsv,"Это старый-добрый Римантадин, только в сиропе.\n","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ...",False,"[Римантадин, сиропе]","[Римантадин, сиропе]","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ..."
2,1_618967.tsv,Но больше всего мне не понравился их размер.\n,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[],[],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
3,5_873342.tsv,"У меня были ужасные боли, даже сидеть не могла.\n","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[],"[сидеть не могла, боли]","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
4,6_592814.tsv,Пропив 5 упаковок это примерно 500-600 рублей ...,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[],[],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1438,4_2533836.tsv,"Но сколько раз мы ни покупали его, я не замеча...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[],[],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1439,1_271739.tsv,Как известно при простуде очень сложно выбрать...,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[простуде],[простуде],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1440,15_1268796.tsv,Больше никогда не воспользуюсь.\n,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[],[],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1441,1_2397151.tsv,"Препарат ""Ликопид"" покупала для лечения герпес...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...",False,"[Ликопид, герпеса]","[Ликопид, герпеса]","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr..."
1442,6_834566.tsv,"Я думал, что возможно это отличное средство дл...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...",False,[профилактики],[профилактики],"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."

In [56]:
ner_sampler.test['y']

,extracted,target
0,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1,"{'Drugname': ['Римантадин'], 'Drugclass': [], ...","{'Drugname': ['Римантадин'], 'Drugclass': [], ..."
2,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
3,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
4,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
...,...,...
1438,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1439,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1440,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."
1441,"{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr...","{'Drugname': ['Ликопид'], 'Drugclass': [], 'Dr..."
1442,"{'Drugname': [], 'Drugclass': [], 'Drugform': ...","{'Drugname': [], 'Drugclass': [], 'Drugform': ..."

## AgentMemorySampler

In [2]:
from llm_val.sampler.AgentMemorySampler import AgentMemorySampler

In [3]:
data_la2 = joblib.load('data/LongAnswerExample.pkl')

sampler_agent_memory = AgentMemorySampler(data_la2)

In [4]:
sampler_agent_memory.test['X'].head()

,question,model_answer,request_id,order_idx,reasoning,history_summarization
0,Есть ли в этом мире подходящий международный и...,boss_lexa На прием платежей и так все страны о...,4,1,Пример внутренних рассуждений агента,Пример суммаризации диалога
1,"Какой курс выбрать для того, чтобы начать рабо...","1. Уроки от SimpleCode. Хорошее повествование,...",2,1,Пример внутренних рассуждений агента,Пример суммаризации диалога
2,Как правильно сделать перенос строки на PHP?,echo выводит строку. Но можно создать цикл по ...,9,1,Пример внутренних рассуждений агента,Пример суммаризации диалога
3,Почему язык Си может работать с низкоуровневым...,"Как уже сказали выше, практически все языки ра...",3,1,Пример внутренних рассуждений агента,Пример суммаризации диалога
4,Как выйти из цикла while?,Походу у вас код коряво отформатирован.\nНу и ...,8,1,Пример внутренних рассуждений агента,Пример суммаризации диалога

In [5]:
sampler_agent_memory.test['y'].head()

   main_metric  another_metric
0            1               1
1            1               0
2            1               1
3            1               0
4            1               0

# TracesSampler

In [6]:
from llm_val.sampler.TracesSampler import TracesSampler

In [7]:
data_traces = pd.read_parquet('data/data_traces.parquet')

traces_sampler = TracesSampler(data_traces)

In [8]:
traces_sampler.test['X'].head()

,final_metric_assessor_1,final_metric_assessor_4,final_metric_assessor_2,final_metric_assessor_5,input_query,final_metric_assessor_3,session_id,output_answer,query_id
0,1.0,NaN,NaN,1.0,Расскажи о состоянии портфеля за месяц,NaN,0.0,Стоимость портфеля за ноябрь-декабрь 2025 года...,b50744e833cefe610331f3d26210ace6
1,NaN,0.0,NaN,1.0,анализ моего портфеля за 25 год,NaN,1.0,"К сожалению, из-за технических проблем не удал...",6bca9eec0de89a8dab6b1f77bb1116a5
2,1.0,NaN,NaN,NaN,инвесткопилка,0.0,2.0,В вашем портфеле отсутствуют данные о продукте...,d1de6397ed80dec217cd79a0ca5fb742
3,1.0,NaN,1.0,NaN,Фонд Рублевые сбережения,NaN,3.0,"В вашем портфеле отсутствуют данные о фонде ""Р...",5908a95011350ff5ce48585d528d6d54
4,NaN,NaN,1.0,1.0,Структура портфеля и риски,NaN,4.0,Основные характеристики портфеля:\n- Общий объ...,486cdbf61e53fb5a97726d7bcaa4b359

In [9]:
traces_sampler.test['y'].head()

   estimation
0         1.0
1         0.0
2         0.0
3         1.0
4         1.0

In [10]:
traces_sampler.test['traces'].head()

,traceid,spanid,name,starttime,endtime
0,b50744e833cefe610331f3d26210ace6,ec6edde186b2ad4a,nodes_classifier,2025-12-16 12:22:03.396299264,2025-12-16 12:22:03.398770944
1,b50744e833cefe610331f3d26210ace6,dc564dc99cf69022,<unknown>,2025-12-16 12:22:03.526691584,2025-12-16 12:22:03.528349696
2,b50744e833cefe610331f3d26210ace6,c8afd12e139fd613,fewshots_node,2025-12-16 12:22:03.401039616,2025-12-16 12:22:03.529744896
3,b50744e833cefe610331f3d26210ace6,350334e70db9f9b8,PromptTemplate,2025-12-16 12:22:03.540996096,2025-12-16 12:22:03.542539776
56,b50744e833cefe610331f3d26210ace6,381642cee078975d,GigaChat,2025-12-16 12:22:03.544433152,2025-12-16 12:22:12.636401152